# Generated by Django 2.2.2 on 2019-08-15 04:11

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File_Data',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.TextField()),
                ('upload_path', models.TextField(null=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modify_timestamp', models.DateTimeField(auto_now=True)),
                ('size', models.FloatField()),
                ('parent_directory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.File_Data')),
            ],
            options={
                'db_table': 'File_Data',
            },
            managers=[
                ('file_datamanager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('storage_name', models.TextField(primary_key=True, serialize=False)),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='storage.File_Data')),
            ],
            options={
                'db_table': 'Storage',
            },
            managers=[
                ('storage_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
