# Generated by Django 2.1.5 on 2019-06-14 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File_Data',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('filename', models.TextField()),
                ('upload_path', models.TextField(null=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modify_timestamp', models.DateTimeField(auto_now=True)),
                ('size', models.FloatField()),
            ],
            options={
                'db_table': 'File_Data',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='storage.File_Data')),
                ('storage_name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'Storage',
            },
        ),
        migrations.AddField(
            model_name='file_data',
            name='parent_directory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.File_Data'),
        ),
    ]
