# Generated by Django 2.1.5 on 2019-02-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('storage_name', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Storage',
            },
        ),
    ]
