# Generated by Django 2.1.5 on 2019-02-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_In_Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modify_timestamp', models.DateTimeField(auto_now=True)),
                ('upload', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'File_In_Storage',
            },
        ),
    ]
