# Generated by Django 2.1.5 on 2019-06-15 07:34

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20190614_1340'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='file_data',
            managers=[
                ('file_datamanager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='storage',
            managers=[
                ('storage_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
