# Generated by Django 2.1.5 on 2019-06-15 08:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20190615_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_data',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
