version: 0.2

phases:
  install:
    commands: 
      - echo "installing requirements"
      - pip install -r requirements.txt
  post_build:
    commands:
      - echo Build completed on `date`
      
artifacts:
  files:
    - '**/*'
