# Generated by Django 2.2.2 on 2019-07-04 07:14

from django.db import migrations, models
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Single_File_Data',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.TextField()),
                ('upload_path', models.TextField(null=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modify_timestamp', models.DateTimeField(auto_now=True)),
                ('size', models.FloatField()),
            ],
            options={
                'db_table': 'Single_File_Data',
            },
            managers=[
                ('single_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
